language: php


php:
  - 7.1
  - 7.2
  - 7.3

env: TEST_PARAMS='-c tests/php.ini'

matrix:
  include:
    - php: 7.4
      env:
        - REPORT_COVERAGE=on
        - TEST_PARAMS='-c tests/php.ini  --coverage coverage.xml --coverage-src src/Mail/FileMailer.php'

script:
  - vendor/bin/tester tests -p php-cgi -s $TEST_PARAMS


before_script:
  - phpenv config-add tests/php.ini
  - composer install

after_script:
 - >
   if [ "$REPORT_COVERAGE" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php coveralls.phar --verbose --config tests/.coveralls.yml
   fi